### ISSUE TITLE
Thank you!!

### ISSUE THREAD

**Issue by marbetschar** [Maia-Everett/valagl#3]
Hi @Maia-Everett,

Thank you so much for providing the `gl.vapi` - it made my day! I'm now tinkering with some GL extensions, and made an additional. manual VAPI for some functions I need. Unfortunately, the Vala compiler throws the error below. Any chance you can point me into the right direction?

Thanks again!

```
error: too many arguments to function ‘__glewCreateMemoryObjectsEXT’
  514 |             GL_EXT.glCreateMemoryObjectsEXT (1, out gl_mem_object);
```

Here's the full VAPI in question:

https://github.com/elementary/gala/blob/675ca4e8f7ae78b8166389b6e81dbc4e0a7d8eaf/vapi/gl-ext.vapi

**Comment by Maia-Everett** [comment]
I haven't tried to compile your code, but my guess would be that the Vala compiler passes the array length before the array by default in the generated C code.

Try adding `[CCode (array_length = false)]` in front of the array in your vapi definition of `glCreateMemoryObjectsEXT`. You can see an example of its use in the definition of, say, `glGenTextures` in `gl.vapi`.

**Comment by marbetschar** [comment]
Seems like that was exactly what was needed. At least, it compiles now and I get some `undefined reference` errors during linking phase. Would be awesome, if you have a tip for this as well. If not, no worries. Happy Easter! :egg: :rabbit: :cake: :balloon: 

```
/usr/bin/ld: plugins/xrdesktop/6fcff83@@gala-xrdesktop@sha/meson-generated_Main.c.o: in function `gala_plugins_xr_desktop_main_upload_xrd_window_gl_external_memory':
/home/USER/Projects/gala/build/../plugins/xrdesktop/Main.vala:425: undefined reference to `__glewCopyImageSubData'
/usr/bin/ld: /home/USER/Projects/gala/build/../plugins/xrdesktop/Main.vala:448: undefined reference to `__glewCopyImageSubData'
/usr/bin/ld: plugins/xrdesktop/6fcff83@@gala-xrdesktop@sha/meson-generated_Main.c.o: in function `gala_plugins_xr_desktop_main_allocate_external_memory':
/home/USER/Projects/gala/build/../plugins/xrdesktop/Main.vala:514: undefined reference to `__glewCreateMemoryObjectsEXT'
/usr/bin/ld: /home/USER/Projects/gala/build/../plugins/xrdesktop/Main.vala:518: undefined reference to `__glewMemoryObjectParameterivEXT'
/usr/bin/ld: /home/USER/Projects/gala/build/../plugins/xrdesktop/Main.vala:521: undefined reference to `__glewGetMemoryObjectParameterivEXT'
/usr/bin/ld: /home/USER/Projects/gala/build/../plugins/xrdesktop/Main.vala:524: undefined reference to `__glewImportMemoryFdEXT'
/usr/bin/ld: /home/USER/Projects/gala/build/../plugins/xrdesktop/Main.vala:546: undefined reference to `__glewTexStorageMem2DEXT'
/usr/bin/ld: /home/USER/Projects/gala/build/../plugins/xrdesktop/Main.vala:555: undefined reference to `__glewDeleteMemoryObjectsEXT'
```

**Comment by Maia-Everett** [comment]
This project uses the GLEW library for robust handling of different OpenGL versions at runtime. If you're using raw OpenGL calls instead of GLEW wrappers, you can replace all instances of `GL/glew.h` with `GL/gl.h` in `gl.vapi`. (And I think `gir_namespace = "GLEW"` with `gir_namespace = "GL"`, too.)
